# Generated by Django 2.1.2 on 2018-12-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blog', '0005_auto_20181221_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
