# Generated by Django 2.1.2 on 2018-12-20 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_blog', '0006_auto_20181221_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_set', to=settings.AUTH_USER_MODEL)),
                ('to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('to_follow', 'from_follow')},
        ),
    ]
